package com.mkyong.domain;

// Generated 21-ago-2014 23:32:20 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * Menu generated by hbm2java
 */
@Entity
public class Menu extends PersistentObject {

	@ManyToOne
//	@Cascade(CascadeType.SAVE_UPDATE)
	private Menu menu;
	private Integer nivel;
	private String nombre;
	private String url;
	private String icono;
	private Byte estado;


	public Menu() {
	}

	public Menu(Menu menu, Integer nivel, String nombre, String url,
			String icono, Byte estado) {
//		this.menu = menu;
		this.nivel = nivel;
		this.nombre = nombre;
		this.url = url;
		this.icono = icono;
		this.estado = estado;
	}



	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "nombre", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "url", length = 120)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "icono", length = 45)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

}
