package ar.com.jsf.domain;
// Generated 21-ago-2014 23:32:20 by Hibernate Tools 3.6.0


import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;





/**
 * Rolmenu generated by hbm2java
 */
@Entity

public class RolMenu extends PersistentObject {
@ManyToOne
//	@Cascade(CascadeType.SAVE_UPDATE)
	private Menu menu;
@ManyToOne
//	@Cascade(CascadeType.SAVE_UPDATE)
	private Rol rol;

    public RolMenu() {
    }

    public RolMenu(Menu menu, Rol rol) {
       this.menu = menu;
       this.rol = rol;
    }

	public Menu getMenu() {
		return menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public Rol getRol() {
		return rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

    



}


