package ar.com.jsf.domain;

// Generated 21-ago-2014 23:32:20 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;


/**
 * Usuario generated by hbm2java
 */
@Entity
public class Usuario extends PersistentObject {

	
	private String usuario;
	@ManyToOne
	private Rol rol;
	private String clave;
	private String email;
	private Byte estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;



	@Column(name = "clave", unique = true, nullable = false, length = 45)
	public String getClave() {
		return this.clave;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaModificacion", nullable = true, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public Rol getRol() {
		return rol;
	}

	@Column(name = "usuario", unique = true, nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	@Column(name = "usuarioCreacion", nullable = false, length = 45)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	@Column(name = "usuarioModificacion", length = 45)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}


	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

}
